### ISSUE TITLE
Cannot get data behind corporate HTTP proxy

### ISSUE THREAD

**Issue by comsaint** [googleapis/python-analytics-data#378]
I have encountered a problem similar to #218. I am also behind a corporate (http) proxy. 

  - OS type and version: `Windows 7`
  - Python version: `3.9.7`
  - pip version: `22.1.2`
  - `google-analytics-data` version: `0.17.0`

In past when using the Analytics Core Reporting API, I set the `HTTP_PROXY` and `HTTPS_PROXY` and it works alright. But this does not seem to work for Data API v1 Beta. I have tested my code outside corporate which works.

I set the `GRPC_TRACE` and `GRPC_VERBOSITY` and below is the traceback:

```
D0810 16:47:51.657000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT tcp_frame_size_tuning               OFF (default:OFF)
D0810 16:47:51.657000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT tcp_rcv_lowat                       OFF (default:OFF)
D0810 16:47:51.680000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT peer_state_based_framing            OFF (default:OFF)
D0810 16:47:51.681000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT memory_pressure_controller          OFF (default:OFF)
D0810 16:47:51.690000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT unconstrained_max_quota_buffer_size OFF (default:OFF)
D0810 16:47:51.690000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT event_engine_client                 OFF (default:OFF)
D0810 16:47:51.691000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT monitoring_experiment               ON  (default:ON)
D0810 16:47:51.691000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT promise_based_client_call           OFF (default:OFF)
D0810 16:47:51.692000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT free_large_allocator                OFF (default:OFF)
D0810 16:47:51.692000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT promise_based_server_call           OFF (default:OFF)
D0810 16:47:51.693000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT transport_supplies_client_latency   OFF (default:OFF)
D0810 16:47:51.693000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT event_engine_listener               OFF (default:OFF)
D0810 16:47:51.693000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT schedule_cancellation_over_write    OFF (default:OFF)
D0810 16:47:51.694000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT trace_record_callops                OFF (default:OFF)
D0810 16:47:51.696000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT event_engine_dns                    OFF (default:OFF)
D0810 16:47:51.697000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT work_stealing                       OFF (default:OFF)
D0810 16:47:51.698000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT client_privacy                      OFF (default:OFF)
D0810 16:47:51.698000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT canary_client_privacy               OFF (default:OFF)
D0810 16:47:51.699000000 16308 src/core/lib/experiments/config.cc:131] gRPC EXPERIMENT server_privacy                      OFF (default:OFF)
D0810 16:47:51.701000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "priority_experimental"
D0810 16:47:51.701000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "outlier_detection_experimental"
D0810 16:47:51.702000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "weighted_target_experimental"
D0810 16:47:51.703000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "pick_first"
D0810 16:47:51.704000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "round_robin"
D0810 16:47:51.704000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "weighted_round_robin"
D0810 16:47:51.705000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "grpclb"
D0810 16:47:51.706000000 16308 src/core/ext/filters/client_channel/resolver/dns/dns_resolver_plugin.cc:51] Using native dns resolver
D0810 16:47:51.707000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "rls_experimental"
D0810 16:47:51.708000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "xds_cluster_manager_experimental"
D0810 16:47:51.708000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "xds_cluster_impl_experimental"
D0810 16:47:51.709000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "cds_experimental"
D0810 16:47:51.714000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "xds_cluster_resolver_experimental"
D0810 16:47:51.715000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "xds_override_host_experimental"
D0810 16:47:51.716000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "xds_wrr_locality_experimental"
D0810 16:47:51.717000000 16308 src/core/lib/load_balancing/lb_policy_registry.cc:47] registering LB policy factory for "ring_hash_experimental"
D0810 16:47:51.718000000 16308 src/core/lib/security/certificate_provider/certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
E0810 16:47:51.719000000 16308 src/core/ext/filters/client_channel/http_proxy.cc:119] 'https' scheme not supported in proxy URI
I0810 16:48:11.800000000 10264 src/core/ext/filters/client_channel/subchannel.cc:707] subchannel 000002BBA9D28B50 {address=ipv4:142.250.204.106:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa052c80, grpc.internal.security_connector=0x2bba9f4a020, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: connect failed (UNKNOWN:socket is null {created_time:"2023-08-10T08:48:11.799377953+00:00"}), backing off for -19004 ms
I0810 16:48:11.815000000 10572 src/core/ext/filters/client_channel/subchannel.cc:662] subchannel 000002BBA9D28B50 {address=ipv4:142.250.204.106:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa052c80, grpc.internal.security_connector=0x2bba9f4a020, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: backoff delay elapsed, reporting IDLE
I0810 16:48:31.815000000 18168 src/core/ext/filters/client_channel/subchannel.cc:707] subchannel 000002BBA9D29250 {address=ipv4:142.250.204.138:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa052ca0, grpc.internal.security_connector=0x2bba9f49300, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: connect failed (UNKNOWN:tcp handshaker shutdown {created_time:"2023-08-10T08:48:31.815055973+00:00"}), backing off for -19016 ms
I0810 16:48:31.830000000 17800 src/core/ext/filters/client_channel/subchannel.cc:662] subchannel 000002BBA9D29250 {address=ipv4:142.250.204.138:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa052ca0, grpc.internal.security_connector=0x2bba9f49300, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: backoff delay elapsed, reporting IDLE

(skipping a lot of similar messages here)

Traceback (most recent call last):
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\google\api_core\grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\grpc\_channel.py", line 1030, in __call__
I0810 16:52:51.902000000  9160 src/core/ext/filters/client_channel/subchannel.cc:707] subchannel 000002BBAA086E80 {address=ipv4:142.250.204.42:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa053560, grpc.internal.security_connector=0x2bba9f491c0, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: connect failed (UNKNOWN:tcp handshaker shutdown {created_time:"2023-08-10T08:52:51.902637165+00:00"}), backing off for -19010 ms
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\grpc\_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "UNKNOWN:Deadline Exceeded {created_time:"2023-08-10T08:52:51.745534928+00:00", grpc_status:4}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\GADataRetriever\main.py", line 101, in <module>
    main()
  File "C:\GADataRetriever\main.py", line 76, in main
    ga_context_ga4.do(start_date=start_date, end_date=end_date)
  File "C:\GADataRetriever\src\GoogleAnalyticsStrategy.py", line 227, in do
I0810 16:52:51.916000000 18168 src/core/ext/filters/client_channel/subchannel.cc:662] subchannel 000002BBAA086E80 {address=ipv4:142.250.204.42:443, args={grpc.client_channel_factory=0x2bba7e01190, grpc.default_authority=analyticsdata.googleapis.com:443, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x2bba9b09aa0, grpc.internal.event_engine=0x2bbaa053560, grpc.internal.security_connector=0x2bba9f491c0, grpc.internal.subchannel_pool=0x2bba667f9a0, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.56.2, grpc.resource_quota=0x2bba667f4e0, grpc.server_uri=dns:///analyticsdata.googleapis.com:443}}: backoff delay elapsed, reporting IDLE
...
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\google\analytics\data_v1beta\services\beta_analytics_data\client.py", line 518, in run_report
    response = rpc(
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\google\api_core\gapic_v1\method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\google\api_core\timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "C:\Users\xxx\.conda\envs\main\lib\site-packages\google\api_core\grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded
D0810 16:52:52.146000000 16308 src/core/lib/surface/init.cc:191] grpc_shutdown starts clean-up now
```

Please kindly assist.

**Comment by fsantosvwfs** [comment]
Hello! How are you?

I have a case where it's working in one environment and not working on another one:
WORKING:
SO: Windows 10 
Python version: 3.11.4
pip version: 23.2.1
pip packages:
Package                  Version
------------------------ --------
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.2.0
google-analytics         0.0.0
google-analytics-data    0.17.0
google-api-core          2.11.1
google-api-python-client 2.94.0
google-auth              2.22.0
google-auth-httplib2     0.1.0
googleapis-common-protos 1.59.1
grpcio                   1.56.2
grpcio-status            1.56.2
httplib2                 0.22.0
idna                     3.4
iso8601                  2.0.0
more-itertools           9.1.0
oauth2client             4.1.3
pip                      23.2.1
proto-plus               1.22.3
protobuf                 4.23.4
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pyparsing                3.1.0
PySocks                  1.7.1
PyYAML                   6.0.1
requests                 2.31.0
rsa                      4.9
setuptools               68.0.0
six                      1.16.0
sob                      1.50.5
uritemplate              4.1.1
urllib3                  1.26.16

NOT WORKING:
SO: RedHat 8.8
Python version: Python 3.11.2
pip version: 23.2.1
pip packages:
Package                  Version
------------------------ --------
cachetools               5.3.1
certifi                  2023.5.7
charset-normalizer       3.2.0
google-analytics         0.0.0
google-analytics-data    0.17.0
google-api-core          2.11.1
google-api-python-client 2.94.0
google-auth              2.22.0
google-auth-httplib2     0.1.0
googleapis-common-protos 1.59.1
grpcio                   1.56.2
grpcio-status            1.56.2
httplib2                 0.22.0
idna                     3.4
iso8601                  2.0.0
more-itertools           9.1.0
oauth2client             4.1.3
pip                      23.2.1
proto-plus               1.22.3
protobuf                 4.23.4
pyasn1                   0.5.0
pyasn1-modules           0.3.0
pyparsing                3.1.0
PySocks                  1.7.1
PyYAML                   6.0.1
requests                 2.31.0
rsa                      4.9
setuptools               68.0.0
six                      1.16.0
sob                      1.50.5
uritemplate              4.1.1
urllib3                  1.26.16

**Comment by parthea** [comment]
The only requirement is that you set the environment variable `HTTP_PROXY` or `HTTPS_PROXY` (or the lowercase versions thereof) as documented [here](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md#grpc-environment-variables). You can also try setting the transport argument in the client itself to use REST instead of gRPC.

For example
` client = data_v1alpha.AlphaAnalyticsDataClient(transport='rest')`

I'm going to close this issue but please open a new issue if you're still having trouble.

**Comment by comsaint** [comment]
@parthea thanks! I set `transport='rest'` and it works like a charm.
