### ISSUE TITLE
request argument parsing issue

### ISSUE THREAD

**Issue by slavanorm** [googleapis/python-analytics-data#379]
hello i use gapandas4 library which under hood uses this library.
i request in report a metric, which has name "conversions:click_play". 
i walked in debugger, and see that python-analytics-data code recieves it properly, but inside it transforms to "conversions[click_play]" and raises error.

#### Steps to reproduce
  1. set up some metric as conversion
  2. request the conversion through api

#### Code example
```
import gapandas4 as gp

key_file_location = "../tokens/ga.json"
account = "X"
property = "Y"

def run(
    dimensions,
    metrics,
    start_date='yesterday',
    end_date='yesterday',
):
    kwargs = dict(
        property=f"properties/{property}",
        dimensions=[
            gp.Dimension(name=e)
            for e in dimensions
        ],
        metrics=[
            gp.Metric(name=e)
            for e in metrics
        ],
        date_ranges=[
            gp.DateRange(start_date=start_date, end_date=end_date)],
    )
   r = gp.RunReportRequest(**kwargs)
   df = gp.query(key_file_location, r, report_type="report")

report_settings = {
        "metrics":[            "conversions:load_lobby",        ],
        "dimensions":[            "date",        ],
    }

run(**report_settings)

```

#### Stack trace
```
/usr/bin/python3 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 64789 --file /Users/v0/Py/sidus/airflow-dag/main_ga_visitors.py
Unable to load extension pydevd_plugins.extensions.types.pydevd_plugin_pandas_types
Connected to pydev debugger (build 223.8617.48)
Traceback (most recent call last):
File "/Library/Python/3.8/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
return callable_(*args, **kwargs)
File "/Library/Python/3.8/site-packages/grpc/_channel.py", line 1030, in call
return _end_unary_response_blocking(state, call, False, None)
File "/Library/Python/3.8/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
raise _InactiveRpcError(state) # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.INVALID_ARGUMENT
details = "Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play]"
debug_error_string = "UNKNOWN:Error received from peer ipv4:142.251.36.42:443 {created_time:"2023-08-21T11:50:19.239056+04:00", grpc_status:3, grpc_message:"Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play]"}"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/Library/Python/3.8/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Metric names must only contain letters, numbers, or _. Received a metric name = conversions[click_play.sidusheroes.com]
python-BaseException
```

**Comment by slavanorm** [comment]
the gp library creates BetaAnalyticsDataClient and calls .run_report(request) method.
request is represented in string in following way:
```
property: "properties/XX"
dimensions {
  name: "date"
}
metrics {
  name: "conversions:load_lobby"
}
date_ranges {
  start_date: "yesterday"
  end_date: "yesterday"
}
keep_empty_rows: true

```

**Comment by slavanorm** [comment]
tried to rename this metric in GUI but i didnt manage to.

**Comment by slavanorm** [comment]
the r variable in abovementioned code is directly passed to run_report call.

**Comment by slavanorm** [comment]
having changed the code to run only this library, the issue is gone

**Comment by slavanorm** [comment]
turns out again that some of the similar metrics are extracting, while others are throwing this error

**Comment by parthea** [comment]
Hi @slavanorm,

See sample code below which doesn't have an error:

https://github.com/googleapis/python-analytics-data/blob/a9962610f2955a3b0e053933b3c95b64c66c8d97/samples/snippets/run_report.py#L42-L53

Are you able to re-create the same error that you're seeing using any of the `run_report_*` samples in https://github.com/googleapis/python-analytics-data/tree/main/samples/snippets?

**Comment by parthea** [comment]
I'm going to transfer this issue to `google-cloud-python` as we are planning to move the code for `google-analytics-data` there in the next 1-2 weeks.
